name: Build APK and Notify Discord

on:
  push:
    branches:
      - dev
      - main
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Get Last 10 Commits
      id: get_commits
      run: |
        echo 'COMMIT_LOG<<EOF' >> $GITHUB_ENV
        git log ${{ github.event.before }}..${{ github.sha }} --pretty=format:"%s" -10 | while IFS= read -r line; do
          echo "$line" >> $GITHUB_ENV
        done
        echo 'EOF' >> $GITHUB_ENV

    - name: Set variables
      run: |
        VER=$(grep -E -o "versionName \".*\"" app/build.gradle | sed -e 's/versionName //g' | tr -d '"')
        SHA=${{ github.sha }}
        VERSION="$VER+${SHA:0:7}"
        echo "Version $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
        cache: gradle
        
    - name: List files in the directory
      run: ls -l

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew assembleDebug
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
          name: Dantotsu
          path: "app/build/outputs/apk/debug/app-debug.apk"
          
    - name: Upload APK to Discord
      shell: bash
      run: |
        commit_messages=$(echo "$COMMIT_LOG")
        contentbody=$( jq -Rsa . <<< "Debug-Build: @everyone **${{ env.VERSION }}**\n\n$commit_messages" )
        curl -F "payload_json={\"content\":${contentbody}}" -F "dantotsu_debug=@app/build/outputs/apk/debug/app-debug.apk" ${{ secrets.DISCORD_WEBHOOK }}
        
